solutions:
  Yoda:
    solution_family: Yoda
    products:
      yoda:
        product_name: Yoda
        components:
          yoda:
            component_name: yoda
            repositories:
            - plan4hub/yoda
      yoda-demo:
        product_name: Yoda Demo
        components:
          yoda-demo:
            component_name: yoda
            repositories:
            - plan4hub/yoda-demo
            - plan4hub/yoda-demo2

queries:
  open-demo-bug: 
    parameters: state=open&labels=T1 - Defect&product=yoda-demo
    description: Retrieve all open Yoda Demo bugs

tokens:
  dev:
    token: 1617e7c6813112772aa7c43080c4ac1e1eda77391094a0f743ca3036b49606b9

# Set of extra fields
extra_fields:
  # Customer should concatenate (with comma) any values
  company:
    rule: extract_label
    pattern: '^C - (.*)'
    separator: ","
  severity:
    rule: extract_label
    pattern: '^S[1-4] - (.*)$'
    # none_value can be specified, but null is actually also the default
    none_value: null
    # If separator is empty then take only first
    separator: ""
    mapping: 'map["Urgent"]="Critical"; map["High"]="Serious";'
  type:
    rule: extract_label
    pattern: '^T[1-9][0-9]? - (.*)$'
    separator: ""
  support:
    rule: binary_label
    pattern: '^Support$'
    value_match: true
    value_nomatch: false
  origin:
    rule: binary_label
    pattern: '^C - .*$'
    value_match: "External"
    value_nomatch: "Internal"
  sfdc_id:
    rule: extract_issue
    field: "title"
    pattern: '^.*[\(]([0-9]+)[\)]$'
  milestone:
    rule: extract_issue
    field: "milestone.title"
  user:
    rule: extract_issue
    field: "user.login"
  assignee:
    rule: extract_issue
    field: "assignee.login"
